test_push_task:
  name: Run tests
  only_if: (${CIRRUS_PR} == '1' || ${CIRRUS_PR} == '2' || ${CIRRUS_PR} == '3' || ${CIRRUS_PR} == '4') && ${CIRRUS_PR_DRAFT} == 'false'
  execution_lock: only-one
  timeout_in: 600m
  on_timeout:
    cleanup_task: sleep 5m

  env:
    A: ENCRYPTED[3e28fac5da9ea8975584bf07bed7419c5785c6ac49821581227d1f39b8edcfa202e94095617afd98cba701e7640c4bd7]
    B: ENCRYPTED[6e3e552eca4062c5b9e7892b010b2f6b80bf8d8320b024bb6a842d37bbf97a213244d8c04949ef36e17063b73b7d39af]
    C: ENCRYPTED[15e1bb79bcea11341559bffb4dc868d0cb0ead827a7b972c05aabe79cb4bfce270b68851947210a944f8fdd8d66f4766]
    D: ENCRYPTED[316da8678c059c858024ce5f6c422b794015f79649c5c052c790fb250d41d7fb9ba8a3db03435bb90cfb027f5f91dc4e]
    E: ENCRYPTED[dbc737544922e773cb62ac9cb946bd3cc89e1b2402c7baf71845d3635f39db0796d30866cff23f71ecd541ab3a54775c]
    F: ENCRYPTED[4812a802ea969b814c882e8882a3ad37304a29ed55503e74b971dea35811b469a5d73a168120f2b04adcceaadd300185]

  compute_engine_instance:
    image_project: debian-cloud
    image: family/debian-13
    architecture: amd64
    platform: linux
    nested_virtualization: false
    cpu: 8
    memory: 32G
    disk: 256

  clone_script: |
    export DEBIAN_FRONTEND=noninteractive
    apt-get update 1>/dev/null 2>&1
    apt-get -yq install git 1>/dev/null 2>&1
    git clone --recursive --branch=master "https://x-access-token:${CIRRUS_REPO_CLONE_TOKEN}@github.com/${CIRRUS_REPO_FULL_NAME}.git" "${CIRRUS_WORKING_DIR}"
    if [ -z "$CIRRUS_PR" ]; then
      git reset --hard "${CIRRUS_CHANGE_IN_REPO}"
    fi

  run_script: printf '%s' "${A}" | base64 -d | bash
