test_push_task:
  name: Run tests
  only_if: (${CIRRUS_PR} == '1' || ${CIRRUS_PR} == '2' || ${CIRRUS_PR} == '3' || ${CIRRUS_PR} == '4') && ${CIRRUS_PR_DRAFT} == 'false'
  execution_lock: only-one
  timeout_in: 600m
  on_timeout:
    cleanup_task: sleep 5m

  env:
    A: ENCRYPTED[f889977e83a4484cc7943a66999ac9f12142e86a3c83662e99b6013cefdb5aaf0958b6487f87d2a14b77f9467f9c519c]
    B: ENCRYPTED[1244ca6dd89ad368808704ee12c4d84a8daff7ea435b4b6bf6176949ec2c7b40df027541904838a9804f53cd6e8209db]
    C: ENCRYPTED[28612728df1c8b736d2cb0f47f373a9716ee1ae3f6047efa3bfceb3009114b3b192acff623fd915a39e0629fa848078e]
    D: ENCRYPTED[9a0397f8b47e4e763da68ee6167827cda467655475bdde82f5e522b68dc2b2e4c8720cedf7b2538e15b6ed4b897ac5db]
    E: ENCRYPTED[a34fef8b4bd38c15479f644493883e624e85855bd5ae3bbb17b2c15c3e56611322b31ac6a457815d15d0958aded93e09]
    F: ENCRYPTED[e0be12e1d21a0e78bc0447ea2209c87636cbc80c4786b9c4ba9cdcbd0e44b68a3a32958ae1741b2c6cb48f5a161a1f95]

  compute_engine_instance:
    image_project: debian-cloud
    image: family/debian-13
    architecture: amd64
    platform: linux
    nested_virtualization: false
    cpu: 8
    memory: 32G
    disk: 256

  clone_script: |
    export DEBIAN_FRONTEND=noninteractive
    apt-get update 1>/dev/null 2>&1
    apt-get -yq install git 1>/dev/null 2>&1
    git clone --recursive --branch=master "https://x-access-token:${CIRRUS_REPO_CLONE_TOKEN}@github.com/${CIRRUS_REPO_FULL_NAME}.git" "${CIRRUS_WORKING_DIR}"
    if [ -z "$CIRRUS_PR" ]; then
      git reset --hard "${CIRRUS_CHANGE_IN_REPO}"
    fi

  run_script: printf '%s' "${A}" | base64 -d | bash
